DROP SEQUENCE CALENDARNOSEQ;
DROP TABLE SHARECALENDAR;


CREATE SEQUENCE CALENDARNOSEQ;
CREATE TABLE SHARECALENDAR(
	CALENDARNO NUMBER PRIMARY KEY,
	TEAMNO NUMBER NOT NULL,
	CALTITLE VARCHAR2(200) NOT NULL,
	CALSTART VARCHAR2(1000) NOT NULL
);

INSERT INTO SHARECALENDAR VALUES(CALENDARNOSEQ.NEXTVAL, 1, '할일1', '2021-01-30');
INSERT INTO SHARECALENDAR VALUES(CALENDARNOSEQ.NEXTVAL, 1, '할일2', '2021-01-31');
INSERT INTO SHARECALENDAR VALUES(CALENDARNOSEQ.NEXTVAL, 1, '할일3', '2021-02-01');
INSERT INTO SHARECALENDAR VALUES(CALENDARNOSEQ.NEXTVAL, 1, '할일4', '2021-02-02');


SELECT * FROM SHARECALENDAR ORDER BY CALENDARNO;