DROP SEQUENCE MYCODE;
DROP TABLE MYCODE;

CREATE SEQUENCE MYCODE NOCACHE;
CREATE TABLE MYCO(
	MYNO NUMBER PRIMARY KEY,
	MYCO NUMBER,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCOMENT VARCHAR2(4000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYCO VALUES(MYCODE.NEXTVAL, 1 , '愿�由ъ옄', '�뒪�봽留� �뀒�뒪�듃','�뒪�봽留� �뀒�뒪�듃', 'Spring mvc �옱諛뗫떎..', SYSDATE);

SELECT * FROM MYCO ORDER BY MYNO DESC;


