DROP SEQUENCE MYCODE;
DROP TABLE MYCODE;

CREATE SEQUENCE MYCODE NOCACHE;
CREATE TABLE MYCO(
	MYNO NUMBER PRIMARY KEY,
	MYCO NUMBER,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCOMENT VARCHAR2(4000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO MYCO VALUES(MYCODE.NEXTVAL, 1 , '관리자', '스프링 테스트','스프링 테스트', 'Spring mvc 재밋다..', SYSDATE);

SELECT * FROM MYCO ORDER BY MYNO DESC;


