DROP SEQUENXE CONTESTSEQ;
DROP TABLE CONTEST;

CREATE SEQUENCE CONTESTSEQ;
CREATE TABLE CONTEST(
	CONTESTNUM NUMBER PRIMARY KEY,
    CONTESTNAME VARCHAR2(50) NOT NULL,
    CONTESTORGANIZER VARCHAR2(50) NOT NULL,
    CONTESTSUBJECTCOMPANY VARCHAR2(50),
    CONTESTSPONSOR VARCHAR2(50),
    CONTESTFIELD VARCHAR2(100) NOT NULL, 
    CONTESTTARGET VARCHAR2(100) NOT NULL,
    CONTESTCOMPANY VARCHAR2(100) NOT NULL,
    CONTESTREWARD VARCHAR2(100) NOT NULL,  
    CONTESTSTART VARCHAR2(200) NOT NULL,
    CONTESTEND VARCHAR2(200) NOT NULL,
    CONTESTCONTENT VARCHAR2(3000) NOT NULL,
    CONTESTFILE VARCHAR2(200),
    CONTESTPAGE VARCHAR2(200),
    CONTESTPERSON VARCHAR2(200) NOT NULL,
    CONTESTPHONE VARCHAR2(200) NOT NULL,
    CONTESTEMAIL VARCHAR2(200) NOT NULL,	
    MEMBERNO NUMBER NOT NULL
);