--회원가입--
DROP SEQUENCE MEMBERSEQ;
DROP TABLE MYMEMBER cascade constraints;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MYMEMBER(
     MEMBER_NO NUMBER PRIMARY KEY,
     MEMBER_ID VARCHAR2(1000) NOT NULL,
     MEMBER_PW VARCHAR2(1000) NOT NULL,
     MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
     MEMBER_GRADE VARCHAR2(30) NOT NULL,
     MEMBER_REGDATE DATE DEFAULT SYSDATE
);

ALTER TABLE MYMEMBER ADD CONSTRAINT UK_MYMEMBER UNIQUE KEY (MEMBER_ID);

INSERT INTO MYMEMBER VALUES(MEMBERSEQ.NEXTVAL, 'MTY','1234','monty420420@naver.com','관리자',sysdate);

SELECT*FROM MYMEMBER;

