
--회원가입--
DROP SEQUENCE MEMBERSEQ;
DROP TABLE MYMEMBER cascade constraints;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MYMEMBER(
     MEMBER_NO NUMBER PRIMARY KEY,
     MEMBER_ID VARCHAR2(1000) NOT NULL,
     MEMBER_PW VARCHAR2(1000) NOT NULL,
     MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
     MEMBER_GRADE VARCHAR2(30) NOT NULL,
     MEMBER_REGDATE DATE DEFAULT SYSDATE
);
ALTER TABLE MYMEMBER ADD CONSTRAINT UK_MYMEMBER UNIQUE (MEMBER_ID);

ALTER TABLE MYMEMBER ADD CONSTRAINTS FK_CC_MNO FOREIGN KEY (MEMBER_NO) REFERENCES MYMEMBER(MEMBER_NO) ON DELETE CASCADE;
           --해당테이블--       --조건--                     --해당테이블에서 지울것--            --포함되어있는것--     


--프로필이미지 컬럼추가--
ALTER TABLE MYMEMBER ADD MEMBER_PHOTO VARCHAR(1000);

INSERT INTO MYMEMBER VALUES(MEMBERSEQ.NEXTVAL, 'MTY','1234','monty420420@naver.com','관리자',sysdate);


SELECT*FROM MYMEMBER;

