--게시판--
DROP SEQUENCE MYNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;
CREATE TABLE MYBOARD(
   MYNO NUMBER PRIMARY KEY,
   MYNAME VARCHAR2(1000) NOT NULL,
   MYTITLE VARCHAR2(2000) NOT NULL,
   MYCONTENT VARCHAR2(4000) NOT NULL,
   MYDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL,'관리자','스프링 테스트','Spring mvc',SYSDATE);
SELECT *FROM MYBOARD ORDER BY MYNO DESC;

----------------------------------------------------------
--회원가입--
DROP SEQUENCE MEMBERSEQ;
DROP TABLE MYMEMBER cascade constraints;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MYMEMBER(
     MEMBER_NO NUMBER PRIMARY KEY,
     MEMBER_ID VARCHAR2(1000) NOT NULL,
     MEMBER_PW VARCHAR2(1000) NOT NULL,
     MEMBER_EMAIL VARCHAR2(1000) NOT NULL,
     MEMBER_GRADE VARCHAR2(30) NOT NULL,
     MEMBER_REGDATE DATE DEFAULT SYSDATE
);

INSERT INTO MYMEMBER VALUES(MEMBERSEQ.NEXTVAL, 'MTY','1234','monty420420@naver.com','관리자',sysdate);

SELECT*FROM MYMEMBER;

