/* 지도 테이블 */
DROP SEQUENXE PLACESEQ;
DROP TABLE PLACE;

CREATE SEQUENCE PLACESEQ;

CREATE TABLE PLACE(
    PNO NUMBER PRIMARY KEY,
    LNG NUMBER NOT NULL,
    LAT NUMBER NOT NULL,
    PTITLE VARCHAR2(50) UNIQUE NOT NULL,
    PCONTENT VARCHAR2(1000) NOT NULL,
    SOKET VARCHAR2(50) NOT NULL,
    COM VARCHAR2(50) NOT NULL,
    PEOPLE VARCHAR2(50) NOT NULL,
    PLIKE NUMBER NOT NULL,
    MEMBERNO NUMBER NOT NULL
);

/* 좋아요 테이블 */
DROP TABLE  PLACE_LIKE;
DROP SEQUENCE LIKESEQ;

CREATE SEQUENCE LIKESEQ;
CREATE TABLE PLACE_LIKE(
    LNO NUMBER PRIMARY KEY,
    PNO NUMBER NOT NULL,
    MEMBERNO NUMBER NOT NULL,
    LIKECHECK NUMBER NOT NULL
);

/* 댓글 테이블 */
DROP TABLE  PLACE_COMMENT;
DROP SEQUENCE PCOMMENTSEQ;
CREATE SEQUENCE PCOMMENTSEQ;
CREATE TABLE PLACE_COMMENT(
    PCNO NUMBER PRIMARY KEY,
    PNO NUMBER NOT NULL,
    PCCONTENT VARCHAR2(500) NOT NULL,
    PCWRITER VARCHAR2(100) NOT NULL,
    MEMBERNO  NUMBER NOT NULL
);

/*제약조건 추가*/
ALTER TABLE PLACE_LIKE
ADD CONSTRAINTS FK_L_PNO FOREIGN KEY (PNO)
REFERENCES PLACE(PNO) ON DELETE CASCADE;

ALTER TABLE PLACE_LIKE
ADD CONSTRAINTS FK_L_MNO FOREIGN KEY (MEMBERNO)
REFERENCES MYMEMBER(MEMBER_NO) ON DELETE CASCADE;

ALTER TABLE PLACE_COMMENT
ADD CONSTRAINTS FK_C_PNO FOREIGN KEY (PNO)
REFERENCES PLACE(PNO) ON DELETE CASCADE;

ALTER TABLE PLACE_COMMENT
ADD CONSTRAINTS FK_C_MNO FOREIGN KEY (MEMBERNO)
REFERENCES MYMEMBER(MEMBER_NO)  ON DELETE CASCADE;