DROP SEQUENXE PLACESEQ;
DROP TABLE PLACE;

CREATE SEQUENCE PLACESEQ;
CREATE TABLE PLACE(
	PNO NUMBER PRIMARY KEY,
	LNG NUMBER NOT NULL,
	LAT NUMBER NOT NULL,
	TITLE NOT NULL,
	CONTENT NOT NULL,
	MEMBERNO NOT NULL
);