/* 지도 테이블 */
DROP SEQUENXE PLACESEQ;
DROP TABLE PLACE;

CREATE SEQUENCE PLACESEQ;

CREATE TABLE PLACE(
    PNO NUMBER PRIMARY KEY,
    LNG NUMBER NOT NULL,
    LAT NUMBER NOT NULL,
    PTITLE VARCHAR2(50) NOT NULL,
    PCONTENT VARCHAR2(1000) NOT NULL,
    SOKET VARCHAR2(50) NOT NULL,
    COM VARCHAR2(50) NOT NULL,
    PEOPLE VARCHAR2(50) NOT NULL,
    PLIKE NUMBER NOT NULL,
    MEMBERNO NUMBER NOT NULL
);

/* 좋아요 테이블 */
DROP TABLE  PLACE_LIKE;
DROP SEQUENCE LIKESEQ;

CREATE SEQUENCE LIKESEQ;
CREATE TABLE PLACE_LIKE(
    LNO NUMBER PRIMARY KEY,
    PNO NUMBER NOT NULL,
    MEMBERNO NUMBER NOT NULL,
    LIKECHECK NUMBER NOT NULL
);

/* 댓글 테이블 */
DROP TABLE  PLACE_REPLY;
DROP SEQUENCE REPLYSEQ;
CREATE SEQUENCE  REPLYSEQ;
CREATE TABLE PLACE_REPLY(
    PRNO NUMBER PRIMARY KEY,
    PNO NUMBER NOT NULL,
    PRCONTENT VARCHAR2(500) NOT NULL,
    PRWRITER VARCHAR2(100) NOT NULL,
    MEMBERNO  NUMBER NOT NULL
);