DROP TABLE SB_FILE;
DROP SEQUENCE SB_FILE_SEQ;

CREATE TABLE SB_FILE(
	FILE_NO NUMBER PRIMARY KEY,
	BNO NUMBER NOT NULL,
	ORG_FILE_NAME VARCHAR2(300) NOT NULL,
	STORED_FILE_NAME VARCHAR2(36) NOT NULL,
	FILE_SIZE NUMBER,
	REGDATE DATE DEFAULT SYSDATE NOT NULL,
	DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL
);

CREATE SEQUENCE SB_FILE_SEQ NOMAXVALUE NOCACHE;

SELECT * FROM SB_FILE;