DROP TABLE SBCOMMENT;
DROP SEQUENCE SBCOMMENT_SEQ;

CREATE TABLE SBCOMMENT(
	RNO NUMBER PRIMARY KEY,
	BNO NUMBER NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	WRITER VARCHAR2(50) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE SBCOMMENT ADD CONSTRAINT SBCOMMENT FOREIGN KEY(BNO) REFERENCES SHAREBOARD(BNO);

CREATE SEQUENCE SBCOMMENT_SEQ START WITH 1 NOCACHE;

SELECT * FROM SBCOMMENT;

INSERT INTO SBCOMMENT(BNO, RNO, CONTENT, WRITER) VALUES(1, SBCOMMENT_SEQ.NEXTVAL, '테스트댓글', '테스트 작성자');