DROP TABLE SHAREBOARD;
DROP SEQUENCE SHAREBOARD_SEQ;

CREATE TABLE SHAREBOARD(
	BNO NUMBER PRIMARY KEY,
	TEAM_NO NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SHAREBOARD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

SELECT * FROM SHAREBOARD;

ALTER TABLE SHAREBOARD ADD(VIEWS NUMBER DEFAULT 0);
