--팀--
DROP SEQUENCE TEAMSEQ;
DROP TABLE TEAM;

CREATE SEQUENCE TEAMSEQ;
CREATE TABLE TEAM(
     TEAM_NO NUMBER PRIMARY KEY,
     MEMBER_NO NUMBER PRIMARY KEY,
     TEAM_NAME VARCHAR2(50) NOT NULL  
);

INSERT INTO TEAM VALUES(TEAMSEQ.NEXTVAL, '협업1');

SELECT*FROM TEAM;

--팀정보--
DROP SEQUENCE TMEMBERSEQ;
DROP TABLE TEAMMEMBER;

CREATE SEQUENCE TMEMBERSEQ;
CREATE TABLE TEAMMEMBER(
     TEAM_NO NUMBER PRIMARY KEY,
     MEMBER_NO NUMBER NOT NULL,
     TEAM_NAME NUMBER NOT NULL  
);

INSERT INTO MYTEAM VALUES(TMEMBERSEQ.NEXTVAL, );

SELECT*FROM MYTEAM;
